baseURL = 'https://urc-kaist.github.io/'
languageCode = 'en-us'
title = 'MR2 KAIST'
theme = 'hugo-book'

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookLogo = 'images/mr2.png'
  BookTheme = 'auto'
  BookRepo = 'https://github.com/URC-kaist/urc-kaist.github.io'
