baseURL = 'https://urc-kaist.github.io/'
languageCode = 'en-us'
title = 'MR2 KAIST'
theme = 'hugo-book'

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content.en'
    weight = 1

  [languages.kr]
    languageName = 'Korean'
    contentDir = 'content.kr'
    weight = 2

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookLogo = 'images/mr2.png'
  BookTheme = 'auto'
  BookRepo = 'https://github.com/URC-kaist/urc-kaist.github.io'
